#!/bin/bash
LAMBDA_CONTAINER_ID_FILE="/tmp/docker_aws_lambda.cid"
LAMBDA_PYTHON_DEPENDENCIES_ZIP="/code/$LAMBDA_PYTHON_DEPENDENCIES_ZIP_NAME"

rm -rf "$LAMBDA_CONTAINER_ID_FILE"
docker build --no-cache -t s3-presigned-aws-lambda-test .
docker run --cidfile "$LAMBDA_CONTAINER_ID_FILE" -d aws-s3-presigned-test
DOCKER_S3_PRESIGNED_AWS_LAMBDA_CID=$(cat "$LAMBDA_CONTAINER_ID_FILE")
docker cp "$DOCKER_S3_PRESIGNED_AWS_LAMBDA_CID:$LAMBDA_PYTHON_DEPENDENCIES_ZIP" .
docker stop "$DOCKER_S3_PRESIGNED_AWS_LAMBDA_CID"
docker rm "$DOCKER_S3_PRESIGNED_AWS_LAMBDA_CID"
